version: '3.8'

services:
  spark_pipeline:
    image: my_custom_spark:latest
    container_name: dynamic_pipeline
    volumes:
      - .:/opt/spark/work
    tty: true
    stdin_open: true

  airflow:
    image: apache/airflow:2.10.2-python3.10
    container_name: airflow_scheduler
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - .:/opt/spark/work
    ports:
      - "8080:8080"
    command: standalone